# Generated by Django 5.2.15 on 2026-06-18 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gerencias', to='organizacion.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
                'ordering': ['estado__nombre', 'nombre'],
                'unique_together': {('nombre', 'estado')},
            },
        ),
    ]
