# Generated by Django 5.2.15 on 2026-06-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('usuarios', '0003_migrate_gerencia_estado_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerencia',
            options={'ordering': ['nombre'], 'verbose_name': 'Gerencia', 'verbose_name_plural': 'Gerencias'},
        ),
        migrations.AlterUniqueTogether(
            name='gerencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.RemoveField(
            model_name='gerencia',
            name='estado',
        ),
    ]
