# Generated by Django 5.2.15 on 2026-07-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_seed_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Centro de Servicio',
                'verbose_name_plural': 'Centros de Servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
