# Generated by Django 5.2.15 on 2026-07-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_centrodeservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodeservicio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='centrodeservicio',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_centrodeservicio_nombre'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_estado_nombre'),
        ),
        migrations.AddConstraint(
            model_name='gerencia',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_gerencia_nombre'),
        ),
    ]
