# Generated by Django 5.2.15 on 2026-07-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_centrodeservicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrodeservicio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
