# seed_data.py — Catalog/organization seed data extracted and refined from CSV
# Julio 2026 — Depurados 66 talleres externos, 896 centros activos


ESTADOS = [
    'Amazonas',
    'Anzoátegui',
    'Apure',
    'Aragua',
    'Barinas',
    'Bolívar',
    'Carabobo',
    'Cojedes',
    'Delta Amacuro',
    'Distrito Capital',
    'Falcón',
    'Guárico',
    'La Guaira',
    'Lara',
    'Miranda',
    'Monagas',
    'Mérida',
    'Nueva Esparta',
    'Portuguesa',
    'Sucre',
    'Trujillo',
    'Táchira',
    'Yaracuy',
    'Zulia',
]


GERENCIAS = [
    'Ambiente, Seguridad e Higiene Ocupacional',
    'Aracoi',
    'Asistencia Técnica (UNECUBA)',
    'Atención al Ciudadano',
    'Auditoría Interna',
    'Automatización de la Información y Tecnología',
    'Bienes y Servicios',
    'CZGNB-62',
    'Centro Nacional de Despacho',
    'Comercialización',
    'Comunicaciones y Relaciones Públicas',
    'Conmovil',
    'Consultoría Jurídica',
    'Control de Emergencias Industriales',
    'Corpoelec Industrial',
    'Desarrollo Social',
    'Despacho de Presidencia',
    'Distribución',
    'EDC Network',
    'FASMEE',
    'Finanzas',
    'Fiscalización',
    'Formación',
    'Fuentes Alternas y Uso Racional de la Energía',
    'Fundelec',
    'Funsasen',
    'Generación Hidroeléctrica',
    'Generación Termoeléctrica',
    'Oficina de Gestión Administrativa',
    'Planificación, Presupuesto, Seguimiento y Control',
    'Presidencia de Corpoelec',
    'Prevención y Protección',
    'Procedatos',
    'Procura',
    'Programación y Control de la Vegetación',
    'Proyectos Especiales del SEN',
    'SERDECO',
    'Servicios Aeronáuticos',
    'Talento Humano',
    'Territorial',
    'Transformadores y Reactores',
    'Transmisión',
    'UNEEE',
    'Vicepresidencia Ejecutiva',
]


CENTROS = [
    ('Anzoátegui', 'Almacen Los Montones'),
    ('Anzoátegui', 'Anaco'),
    ('Anzoátegui', 'Anzoategui'),
    ('Anzoátegui', 'Barbacoa I'),
    ('Anzoátegui', 'Centro De Servicio El Tigre'),
    ('Anzoátegui', 'Ciau Anaco'),
    ('Anzoátegui', 'Ciau Barcelona I'),
    ('Anzoátegui', 'Ciau Barcelona Ii'),
    ('Anzoátegui', 'Ciau Clarines'),
    ('Anzoátegui', 'Ciau El Morro'),
    ('Anzoátegui', 'Ciau El Tigre'),
    ('Anzoátegui', 'Ciau El Tigrito'),
    ('Anzoátegui', 'Ciau Puerto La Cruz'),
    ('Anzoátegui', 'Cs Anaco'),
    ('Anzoátegui', 'Cs Clarines'),
    ('Anzoátegui', 'Cs El Tigre'),
    ('Anzoátegui', 'Cs Metropolitano'),
    ('Anzoátegui', 'Cs Pariaguan'),
    ('Anzoátegui', 'Edif Chinchon'),
    ('Anzoátegui', 'Edif Damasco'),
    ('Anzoátegui', 'Edif Guanire'),
    ('Anzoátegui', 'Edif Simon Rodriguez'),
    ('Anzoátegui', 'Edif. Simon Rodriguez'),
    ('Anzoátegui', 'Edificio Guanire'),
    ('Anzoátegui', 'El Tigre'),
    ('Anzoátegui', 'Est. Edificio Guanire'),
    ('Anzoátegui', 'Est. El Esfuerzo - Cantaura'),
    ('Anzoátegui', 'Estacion Sede Guanire'),
    ('Anzoátegui', 'Estacionamiento Simon Rodriguez'),
    ('Anzoátegui', 'Global Servi J C.a'),
    ('Anzoátegui', 'Planta Alfredo Salazar'),
    ('Anzoátegui', 'Planta Guanta'),
    ('Anzoátegui', 'Pto La Cruz Edif Chinchon'),
    ('Anzoátegui', 'Robado'),
    ('Anzoátegui', 'S / E El Tigre'),
    ('Anzoátegui', 'S / E. Canoa'),
    ('Anzoátegui', 'S / E. Tigre I'),
    ('Anzoátegui', 'Sub. Est, El Tigre'),
    ('Anzoátegui', 'Sur America C.a'),
    ('Apure', 'Apure'),
    ('Apure', 'Atencion Especializada San Fernando'),
    ('Apure', 'Averias Elorza'),
    ('Apure', 'Biruaca'),
    ('Apure', 'C.s. San Fernando'),
    ('Apure', 'Comercial Biruaca'),
    ('Apure', 'Comercial Elorza'),
    ('Apure', 'Comercial Guasdualito'),
    ('Apure', 'Comercial Mantecal'),
    ('Apure', 'Comercial San Fernando'),
    ('Apure', 'Comercialsan Fernando'),
    ('Apure', 'Coordinacion De Atencion Al Publico Y Operativa Comercial Cs Tp C San Fdo - Apure.'),
    ('Apure', 'Distribucion Achaguas'),
    ('Apure', 'Distribucion Bruzual'),
    ('Apure', 'Distribucion Guasdualito'),
    ('Apure', 'Distribucion Mantecal'),
    ('Apure', 'Distribucion Pedro Camejo'),
    ('Apure', 'Distribucion San Fernando'),
    ('Apure', 'Distribucion Seccion De Linea Arichuna'),
    ('Apure', 'Distribucion Seccion De Lineas Palmarito'),
    ('Apure', 'Distrito Elorza'),
    ('Apure', 'Elorza'),
    ('Apure', 'Flota Apure'),
    ('Apure', 'Gerencia General De Control De Emergencia Industriales Bcei'),
    ('Apure', 'Gerencia General De Programacion Y Control De Vegetacion'),
    ('Apure', 'Gerencia Regional Los Llanos / Supervision Estadal Del Estado Apure, De Comunicaciones Y Relacion...'),
    ('Apure', 'Gerencia Territoroal Apure'),
    ('Apure', 'Guasdualito'),
    ('Apure', 'Los Llanos'),
    ('Apure', 'Mantenimiento Achaguas'),
    ('Apure', 'Mantenimiento Biruaca'),
    ('Apure', 'Mantenimiento Bruzual'),
    ('Apure', 'Mantenimiento El Nula'),
    ('Apure', 'Mantenimiento Elorza'),
    ('Apure', 'Mantenimiento Especializado San Fernando'),
    ('Apure', 'Mantenimiento Guasdualito'),
    ('Apure', 'Mantenimiento Nula'),
    ('Apure', 'Mantenimiento Pedro Camejo'),
    ('Apure', 'Mantenimiento San Fernando'),
    ('Apure', 'Palmarito'),
    ('Apure', 'San Fernando'),
    ('Apure', 'San Fernando Apure'),
    ('Apure', 'San Fernando De'),
    ('Apure', 'San Fernando De Apure'),
    ('Aragua', 'Almacen Dara'),
    ('Aragua', 'Aragua'),
    ('Aragua', 'C / S Urdaneta'),
    ('Aragua', 'Cagua'),
    ('Aragua', 'La Victoria'),
    ('Aragua', 'Mariño'),
    ('Aragua', 'Ocumare'),
    ('Aragua', 'Ocumare De La Costa'),
    ('Aragua', 'S / E Horqueta'),
    ('Aragua', 'S / E San Ignacio'),
    ('Aragua', 'San Sebastian'),
    ('Aragua', 'Tejerias'),
    ('Aragua', 'Turmero'),
    ('Aragua', 'Victoria'),
    ('Barinas', 'Alcaldia De Arismendi'),
    ('Barinas', 'Almacen Secundario'),
    ('Barinas', 'Asho Planta Peña Larga'),
    ('Barinas', 'Barinas'),
    ('Barinas', 'C.s / Chacao'),
    ('Barinas', 'Centro De Servicio El Convento Caracas'),
    ('Barinas', 'Centro De Servicios Sabaneta'),
    ('Barinas', 'Ciau Barinas I'),
    ('Barinas', 'Ciau Barinitas'),
    ('Barinas', 'Ciau El Canton'),
    ('Barinas', 'Ciau.sta. Barbara'),
    ('Barinas', 'Ciudad Nutria'),
    ('Barinas', 'Comercial'),
    ('Barinas', 'Cs Socopo / Cdad Bolivia'),
    ('Barinas', 'Div. De Administracion De Vehiculos'),
    ('Barinas', 'Div. De Bienes Y Servicios Infraestructura'),
    ('Barinas', 'Division Adecuacion Y Mejora Hidroelectrica Generacion Los Llanos'),
    ('Barinas', 'Dtto Libertad'),
    ('Barinas', 'Edificio De Sede De Copoelec'),
    ('Barinas', 'Edificio Sede Corpoelec Barinas'),
    ('Barinas', 'Emplazamiento Arismendi'),
    ('Barinas', 'Fondo Auto Administrado De Salud Fasmee'),
    ('Barinas', 'Fondo Auto Administrado De Salud Fasmee “planta Paez “'),
    ('Barinas', 'Generacion Estadal Termoelectrica Plata Santa Ines'),
    ('Barinas', 'Gerencia De Fiscalizacion Estadal Mppee'),
    ('Barinas', 'Gerencia Del Centro De Servicios Socopo'),
    ('Barinas', 'Gerencia Estadal Ambiente, Seguridad E Higiene Ocupacional (asho)'),
    ('Barinas', 'Gerencia Estadal Bienes Y Servicios'),
    ('Barinas', 'Gerencia Estadal De Automatizacion De La Informacion Y Tecnologia (atit)'),
    ('Barinas', 'Gerencia Estadal De Fuentes Alternas Y Uso Racional De La Energia'),
    ('Barinas', 'Gerencia Estadal Programacion Y Control De La Vegetacion'),
    ('Barinas', 'Gerencia Estadal Territorial'),
    ('Barinas', 'Gerencia Estadal Transmision'),
    ('Barinas', 'Gerencia Regional De Comunicaciones Y Relaciones Publicas'),
    ('Barinas', 'Gerencia Regional De Proyecto Mayores Los Llanos'),
    ('Barinas', 'Gerencia Regional Div. Generacion Los Llanos'),
    ('Barinas', 'Jefatura De Lineas Barinitas'),
    ('Barinas', 'Jefatura De Lineas Sta Barbara'),
    ('Barinas', 'Jim Tires C.a, Ubicado En Palo Verde, Edo Miranda|'),
    ('Barinas', 'Mtto Averia'),
    ('Barinas', 'Mtto Especializado'),
    ('Barinas', 'Ofic Barrancas'),
    ('Barinas', 'Planta Guanapa'),
    ('Barinas', 'Planta Masparro'),
    ('Barinas', 'Planta Paez'),
    ('Barinas', 'Planta Peña Larga'),
    ('Barinas', 'Planta Termobarrancas'),
    ('Barinas', 'Planta Termoelectrica Batalla De Santa Ines'),
    ('Barinas', 'Sede Transmision'),
    ('Barinas', 'Unecuba'),
    ('Barinas', 'Unecuba, Se Encuntra Ciudad De Caracas'),
    ('Bolívar', 'Alcaldia Bolivariana Del Orinico'),
    ('Bolívar', 'Antigua Sede Elebol'),
    ('Bolívar', 'Asistencia Tecnica'),
    ('Bolívar', 'Bcei Caruachi'),
    ('Bolívar', 'Bolivar'),
    ('Bolívar', 'Caicara'),
    ('Bolívar', 'Campamento Guri'),
    ('Bolívar', 'Campamento Macagua'),
    ('Bolívar', 'Canaima'),
    ('Bolívar', 'Caracas En La Gerencia De Asho'),
    ('Bolívar', 'Caruachi'),
    ('Bolívar', 'Cd Bolivar'),
    ('Bolívar', 'Cd. Bolivar'),
    ('Bolívar', 'Centro Administrativo Puerto Ayacucho'),
    ('Bolívar', 'Centro De Mantenimiento Macagua'),
    ('Bolívar', 'Centro De Servicios Ezequiel Zamora'),
    ('Bolívar', 'Ciudad Bolivar'),
    ('Bolívar', 'Ciudad Piar'),
    ('Bolívar', 'Comando De La Guardia'),
    ('Bolívar', 'Comando De La Guardia Macagua.'),
    ('Bolívar', 'Desincorporado'),
    ('Bolívar', 'Edif Sede Altavista'),
    ('Bolívar', 'Edificio Sede Alta Vista'),
    ('Bolívar', 'Edificio Sede Y Torre Corporativa'),
    ('Bolívar', 'El Callao'),
    ('Bolívar', 'El Palmar'),
    ('Bolívar', 'En Taller Mecánico Macagua'),
    ('Bolívar', 'Estacionamiento Campenon Macagua'),
    ('Bolívar', 'Estacionamiento De Bomberos Guri'),
    ('Bolívar', 'Estacionamiento Judicial La Reo I San Felix'),
    ('Bolívar', 'Estacionamiento Judicial La Reo Ii Upata'),
    ('Bolívar', 'Estacionamiento Taller Macagua'),
    ('Bolívar', 'Guasipati'),
    ('Bolívar', 'Guayana A'),
    ('Bolívar', 'Guri'),
    ('Bolívar', 'Las Claritas'),
    ('Bolívar', 'Luepa Santa Elena'),
    ('Bolívar', 'Macagua'),
    ('Bolívar', 'Macagua Almacen 8'),
    ('Bolívar', 'Macagua Campenon'),
    ('Bolívar', 'Macagua Casa N.º 22'),
    ('Bolívar', 'Macagua Patio 400'),
    ('Bolívar', 'Malena'),
    ('Bolívar', 'Patio 400'),
    ('Bolívar', 'Patio 4000'),
    ('Bolívar', 'Patio 765 Guri'),
    ('Bolívar', 'Patio 765 Kva Guri'),
    ('Bolívar', 'Patio Campenon Macagua'),
    ('Bolívar', 'Planta Caruachi'),
    ('Bolívar', 'Planta Guri'),
    ('Bolívar', 'Planta Sidor'),
    ('Bolívar', 'Población De El Callao'),
    ('Bolívar', 'Puerto Ordaz'),
    ('Bolívar', 'Red Troncal'),
    ('Bolívar', 'S / E Bolivar La Candelaria'),
    ('Bolívar', 'S / E Callao'),
    ('Bolívar', 'S / E Canoa'),
    ('Bolívar', 'S / E Cañafistola'),
    ('Bolívar', 'S / E El Callao'),
    ('Bolívar', 'S / E Guayana A'),
    ('Bolívar', 'S / E Guayana A - B'),
    ('Bolívar', 'S / E Guayana A Y B'),
    ('Bolívar', 'S / E Guayana Ab'),
    ('Bolívar', 'S / E Guayana B'),
    ('Bolívar', 'S / E La Candelaria Bolivar'),
    ('Bolívar', 'S / E La Canoa'),
    ('Bolívar', 'S / E Las Claritas'),
    ('Bolívar', 'S / E Malena'),
    ('Bolívar', 'S / E San Felix'),
    ('Bolívar', 'S / E Santa Elena De Uairen'),
    ('Bolívar', 'S / E Unare'),
    ('Bolívar', 'S / Malena'),
    ('Bolívar', 'S / N'),
    ('Bolívar', 'San Francisco De La Paragua'),
    ('Bolívar', 'San Ignacio De Yuruani'),
    ('Bolívar', 'San Rafael De Atabapo.'),
    ('Bolívar', 'Santa Elena'),
    ('Bolívar', 'Santa Elena De Uairen'),
    ('Bolívar', 'Se Encuentra En Caracas'),
    ('Bolívar', 'Sede Antigua Elebol Cdad Bolivar'),
    ('Bolívar', 'Sede Avda. Las Americas'),
    ('Bolívar', 'Sede Ciudad Bolivar'),
    ('Bolívar', 'Sede Planta Vieja Ciudad Bolívar'),
    ('Bolívar', 'Sede Taller Mecanico Simon Rodríguez Anzoategui'),
    ('Bolívar', 'Sub - Estacion Guayana B'),
    ('Bolívar', 'Sub - Estacion Malena / Caicara'),
    ('Bolívar', 'Sub - Estacion Unare'),
    ('Bolívar', 'Sub - Estaciòn Malena'),
    ('Bolívar', 'Sub Estacion Malena'),
    ('Bolívar', 'Subestacion Farallones'),
    ('Bolívar', 'Subestacion Malena'),
    ('Bolívar', 'Subestacion Palital'),
    ('Bolívar', 'Subestación Patio 400 Macagua'),
    ('Bolívar', 'Subestación Santa Elena'),
    ('Bolívar', 'Taller Guri'),
    ('Bolívar', 'Taller Mecanico Guri'),
    ('Bolívar', 'Taller Mecánico Guri'),
    ('Bolívar', 'Taller Mecánico Macagua'),
    ('Bolívar', 'Tocoma'),
    ('Bolívar', 'Tumero'),
    ('Bolívar', 'Unare'),
    ('Bolívar', 'Unexee'),
    ('Bolívar', 'Upata'),
    ('Carabobo', 'A Nivel Ncional'),
    ('Carabobo', 'Almacen (planta Centro)'),
    ('Carabobo', 'Almacen Carabobo'),
    ('Carabobo', 'Almacen El Bosque'),
    ('Carabobo', 'Almacen Gt Ii'),
    ('Carabobo', 'Almacen Los Guayos'),
    ('Carabobo', 'Almacen Michelena'),
    ('Carabobo', 'Arenosa 765'),
    ('Carabobo', 'Bejuma - Montalban - Miranda'),
    ('Carabobo', 'C / S La Yaguara'),
    ('Carabobo', 'Capital - Calidad De Apoyo A Edc Network'),
    ('Carabobo', 'Carabobo'),
    ('Carabobo', 'Carlos Arvelo'),
    ('Carabobo', 'Centro De Distribución San Carlos'),
    ('Carabobo', 'Centro De Servicio Valencia Sur'),
    ('Carabobo', 'Comercial Torre 4'),
    ('Carabobo', 'Eje Costero'),
    ('Carabobo', 'Eje Costero (se Encuentra En La Gobernacion)'),
    ('Carabobo', 'Eje Costero - Funsasen'),
    ('Carabobo', 'Gobernacion Del Estado Carabobo'),
    ('Carabobo', 'Guacara - San Joaquin - Mariara'),
    ('Carabobo', 'Libertador'),
    ('Carabobo', 'Los Guayos'),
    ('Carabobo', 'Planta Centro'),
    ('Carabobo', 'Planta Termoelectrica La Quizanda'),
    ('Carabobo', 'Procura'),
    ('Carabobo', 'Puerto Cabello'),
    ('Carabobo', 'Reparacion Taller Automotrices St24.ca'),
    ('Carabobo', 'S / E Arenosa 765'),
    ('Carabobo', 'San Diego - Los Guayos'),
    ('Carabobo', 'Sede S / E Cardenera'),
    ('Carabobo', 'Sub Estacion San Ignacio'),
    ('Carabobo', 'Subestacion La Arenosa'),
    ('Carabobo', 'Torre 4 / Carabobo'),
    ('Carabobo', 'Valencia'),
    ('Carabobo', 'Valencia Norte'),
    ('Carabobo', 'Valencia Sur'),
    ('Cojedes', 'Distribucion San Carlos'),
    ('Cojedes', 'Distribuidora Hl'),
    ('Cojedes', 'Gerencia Automatizacion De La Informacion Y Tecnologia'),
    ('Cojedes', 'Gerencia Bienes Y Servicios'),
    ('Cojedes', 'Gerencia Brigada De Control De Incendios'),
    ('Cojedes', 'Gerencia Centro Estadal De Despacho'),
    ('Cojedes', 'Gerencia Comercializacion'),
    ('Cojedes', 'Gerencia De Ambiente, Seguridad E Higiene Ocupacional'),
    ('Cojedes', 'Gerencia De Brigada De Control De Incendios'),
    ('Cojedes', 'Gerencia De Fuentes Alternas Y Uso Racional Y Eficiente De La Energia'),
    ('Cojedes', 'Gerencia Distribucion'),
    ('Cojedes', 'Gerencia Fiscalizacion'),
    ('Cojedes', 'Gerencia Prevencion Y Proteccion'),
    ('Cojedes', 'Gerencia Procura'),
    ('Cojedes', 'Gerencia Programacion Y Control De La Vegetacion'),
    ('Cojedes', 'Gerencia Transmision'),
    ('Cojedes', 'San Carlos'),
    ('Delta Amacuro', 'Calle La Planta - Tucupita'),
    ('Delta Amacuro', 'Delta Amacuro'),
    ('Delta Amacuro', 'Dtto. Tucupita'),
    ('Delta Amacuro', 'Galpon De Distrito Corpoelec Tucupita Delta Amacuro'),
    ('Delta Amacuro', 'Galpon Tucupita'),
    ('Delta Amacuro', 'Modulo Casacoima Corpoelec Tucupita Delta Amacuro'),
    ('Delta Amacuro', 'Modulo De Oficina Comercial Tucupita'),
    ('Delta Amacuro', 'Sub Estacion Tucupita Delta Amacuro'),
    ('Distrito Capital', '(lh) Valencia'),
    ('Distrito Capital', 'Alfamat'),
    ('Distrito Capital', 'Almacen Chacao'),
    ('Distrito Capital', 'Almacen La Yaguara'),
    ('Distrito Capital', 'Asamblea Nacional'),
    ('Distrito Capital', 'Buena Vista'),
    ('Distrito Capital', 'C / S Chacao'),
    ('Distrito Capital', 'C / S Chacao Almacen'),
    ('Distrito Capital', 'Capital'),
    ('Distrito Capital', 'Caracas'),
    ('Distrito Capital', 'Centro De Servicio Cahacao'),
    ('Distrito Capital', 'Centro De Servicio Capital'),
    ('Distrito Capital', 'Centro De Servicio La Yaguara'),
    ('Distrito Capital', 'Centro De Servico Convento'),
    ('Distrito Capital', 'Chacao'),
    ('Distrito Capital', 'Cnd'),
    ('Distrito Capital', 'Colonia Tovar'),
    ('Distrito Capital', 'Convento'),
    ('Distrito Capital', 'Corpozulia'),
    ('Distrito Capital', 'Cs Chacao'),
    ('Distrito Capital', 'Cuartel De La Montaña'),
    ('Distrito Capital', 'Diekman / Montezuma / Las Acacias'),
    ('Distrito Capital', 'Edificio Sede Santa Teresa (miranda)'),
    ('Distrito Capital', 'El Convento'),
    ('Distrito Capital', 'El Marques'),
    ('Distrito Capital', 'El Marqués'),
    ('Distrito Capital', 'El Rosal'),
    ('Distrito Capital', 'Fuerte Tiuna'),
    ('Distrito Capital', 'Jim Taire'),
    ('Distrito Capital', 'Jim Taire 30000'),
    ('Distrito Capital', 'La Yaguara'),
    ('Distrito Capital', 'Miisterio'),
    ('Distrito Capital', 'Ministerio'),
    ('Distrito Capital', 'Ministterio'),
    ('Distrito Capital', 'Minsiterio'),
    ('Distrito Capital', 'Montano (santa Paula)'),
    ('Distrito Capital', 'Montezuma'),
    ('Distrito Capital', 'Montezuma / Serline'),
    ('Distrito Capital', 'Mppee / San Berbardino'),
    ('Distrito Capital', 'Olimpus'),
    ('Distrito Capital', 'Olympus'),
    ('Distrito Capital', 'Por Ubicar'),
    ('Distrito Capital', 'Reibucado La Guaira'),
    ('Distrito Capital', 'Sala De Control Santa Rosa'),
    ('Distrito Capital', 'San Bernardino'),
    ('Distrito Capital', 'Santa Rosa'),
    ('Distrito Capital', 'Sarria'),
    ('Distrito Capital', 'Sede Funsasen En Mampote'),
    ('Distrito Capital', 'Serline'),
    ('Distrito Capital', 'Serline / Montezuma'),
    ('Distrito Capital', 'Servicio Integrales Re, C.a.'),
    ('Distrito Capital', 'Servicios Integrales (barquisimeto)'),
    ('Distrito Capital', 'Taler Electra'),
    ('Distrito Capital', 'Taller Bello Monte'),
    ('Distrito Capital', 'Taller Buena Vista'),
    ('Distrito Capital', 'Taller Convento'),
    ('Distrito Capital', 'Taller Los Cortijos'),
    ('Distrito Capital', 'Torre El Marques'),
    ('Distrito Capital', 'Torre El Marqués'),
    ('Distrito Capital', 'Torre General'),
    ('Distrito Capital', 'Torre Las Mercedes'),
    ('Distrito Capital', 'Torre Olympia'),
    ('Distrito Capital', 'Torre San Bernardino'),
    ('Distrito Capital', 'Yaguara'),
    ('Falcón', 'Adicora'),
    ('Falcón', 'Alcaldia De San Luis'),
    ('Falcón', 'C.a.r'),
    ('Falcón', 'Cauajarito (zulia)'),
    ('Falcón', 'Centro De Servicio Chichiriviche'),
    ('Falcón', 'Centro De Servicio Churuguara'),
    ('Falcón', 'Centro De Servicio Zarabon'),
    ('Falcón', 'Centro Sur (zulia)'),
    ('Falcón', 'Ciau Tucacas'),
    ('Falcón', 'Comercializacion'),
    ('Falcón', 'Coord. De Transmision'),
    ('Falcón', 'Cota (zulia)'),
    ('Falcón', 'Distribuidora Multiple Martinez (coro)'),
    ('Falcón', 'Distrito Churuguara'),
    ('Falcón', 'Distrito Coro'),
    ('Falcón', 'Distrito Dabajuro'),
    ('Falcón', 'Distrito Mirimire'),
    ('Falcón', 'Distrito Pto Fijo'),
    ('Falcón', 'Distrito Punto Fijo'),
    ('Falcón', 'Distrito Tucacas'),
    ('Falcón', 'Distritopunto Fijo'),
    ('Falcón', 'Edificio Sede De Corpoelec'),
    ('Falcón', 'Estac. Alcaldia Mirimire'),
    ('Falcón', 'Estac. Trans. Maicillal'),
    ('Falcón', 'Estac. Transito Dabajuro'),
    ('Falcón', 'Falcon'),
    ('Falcón', 'La Vela'),
    ('Falcón', 'Lineas Mirimire'),
    ('Falcón', 'Lineas Pueblo Nuevo'),
    ('Falcón', 'Los Taques'),
    ('Falcón', 'Oficina Comercial Punto Fijo'),
    ('Falcón', 'Oficina Coro'),
    ('Falcón', 'Oficina Dabajuro'),
    ('Falcón', 'Oficina Mene Mauroa'),
    ('Falcón', 'Oficina Mirimire'),
    ('Falcón', 'Oficina Pueblo Nuevo'),
    ('Falcón', 'Oficina Punto Fijo'),
    ('Falcón', 'Oficina San Luis'),
    ('Falcón', 'Oficina Santa Cruz'),
    ('Falcón', 'Oficina Tucacas'),
    ('Falcón', 'Oficina Urumaco'),
    ('Falcón', 'Parque Eolico'),
    ('Falcón', 'Parque Eolico Paraguana'),
    ('Falcón', 'Planta Coro'),
    ('Falcón', 'Planta Coro - Generacion'),
    ('Falcón', 'Planta De Recuperación De Transformadores'),
    ('Falcón', 'Planta Josefa Camejo'),
    ('Falcón', 'Planta Punto Fijo'),
    ('Falcón', 'Servicios De Transporte'),
    ('Falcón', 'Servs De Transporte'),
    ('Falcón', 'Servs. De Transporte'),
    ('Falcón', 'Subestacion Pueblo Nuevo'),
    ('Falcón', 'Subestacion Urumaco'),
    ('Falcón', 'Taller Corpoelec C / S Chacao (ccs)'),
    ('Falcón', 'Tecnovial ( San Diego - Eso Carabobo)'),
    ('Falcón', 'Workshop Paraguana (punto Fijo)'),
    ('Falcón', 'Zona Franca Punto Fijo'),
    ('Guárico', 'Altagracia De Orituco'),
    ('Guárico', 'Calabozo'),
    ('Guárico', 'Camaguan'),
    ('Guárico', 'Centro De Servicios Eleggua Miranda'),
    ('Guárico', 'Centro De Servicos Chacao'),
    ('Guárico', 'El Socorro'),
    ('Guárico', 'El Sombrero'),
    ('Guárico', 'Electro Construcciones Y Representaciones C.a'),
    ('Guárico', 'Electro Construcciones Y Representaciones C.a Mariara Valencia'),
    ('Guárico', 'Espino'),
    ('Guárico', 'Guarico'),
    ('Guárico', 'Las Mercedes'),
    ('Guárico', 'San Geronimo'),
    ('Guárico', 'San Juan De Los Morros'),
    ('Guárico', 'Tucupido'),
    ('Guárico', 'Valle De La Pascua'),
    ('Guárico', 'Zaraza'),
    ('La Guaira', 'C / S Guanape'),
    ('La Guaira', 'Centro De Servicio Guanape'),
    ('La Guaira', 'Complejo Generador Josefa Joaquina Sánchez Bastidas'),
    ('La Guaira', 'Guanape'),
    ('La Guaira', 'La Guaira'),
    ('La Guaira', 'Tacoa'),
    ('Lara', 'Algimiro Gabaldon'),
    ('Lara', 'Cabudare'),
    ('Lara', 'Carora'),
    ('Lara', 'Centro De Servicio Pala Vecino'),
    ('Lara', 'Centro De Servicio Palavecino'),
    ('Lara', 'Centro Servicio Quibor - Tocuyo'),
    ('Lara', 'Cs Barquisimeto'),
    ('Lara', 'Cs Carora'),
    ('Lara', 'Cs Duaca'),
    ('Lara', 'Cs Palavecino'),
    ('Lara', 'Cs Quibor'),
    ('Lara', 'Cs Quibor - Tocuyo'),
    ('Lara', 'Cs Quibor Tocuyo'),
    ('Lara', 'Desarrollo'),
    ('Lara', 'Duaca'),
    ('Lara', 'Edif Martins Mulder'),
    ('Lara', 'Edificio Carora'),
    ('Lara', 'Edificio Sede'),
    ('Lara', 'Gabaldon'),
    ('Lara', 'Infraestructura Lhf'),
    ('Lara', 'Lh'),
    ('Lara', 'Lhf'),
    ('Lara', 'Mantenimiento Especializado'),
    ('Lara', 'Martinus Molder'),
    ('Lara', 'Nueva Segovia'),
    ('Lara', 'Palavecino'),
    ('Lara', 'Patio Servicios Generales'),
    ('Lara', 'Planata Ii - Iii'),
    ('Lara', 'Planta Ii'),
    ('Lara', 'Planta Ii - Iii'),
    ('Lara', 'Planta Ii De Lara'),
    ('Lara', 'Plata Ii'),
    ('Lara', 'Procura Almacen Lhf'),
    ('Lara', 'Quibor'),
    ('Lara', 'Quibor - Tocuyo'),
    ('Lara', 'Sede'),
    ('Lara', 'Sede Carora'),
    ('Lara', 'Sede Cubana'),
    ('Lara', 'Servicio Generales'),
    ('Lara', 'Servicios Generales'),
    ('Lara', 'Taller Flota'),
    ('Lara', 'Taller Servicios Generales'),
    ('Lara', 'Vargas'),
    ('Lara', 'Zona Iv'),
    ('Miranda', 'C / S Barbecho'),
    ('Miranda', 'C / S Charallave'),
    ('Miranda', 'C / S El Barbecho'),
    ('Miranda', 'C / S Guarenas Guatire'),
    ('Miranda', 'C / S Higuerote'),
    ('Miranda', 'C / S Santa Teresa'),
    ('Miranda', 'Centro De Servicio Barbecho'),
    ('Miranda', 'Centro De Servicio Charallave'),
    ('Miranda', 'Centro De Servicio Cua'),
    ('Miranda', 'Centro De Servicio El Barbecho'),
    ('Miranda', 'Centro De Servicio Guarenas'),
    ('Miranda', 'Centro De Servicio Guarenas - Guatire'),
    ('Miranda', 'Centro De Servicio Guarenas Guatire'),
    ('Miranda', 'Centro De Servicio Higuerote'),
    ('Miranda', 'Centro De Servicio Rio Chico'),
    ('Miranda', 'Centro De Servicio Santa Teresa'),
    ('Miranda', 'Centro De Servicio Santa Teresaiii'),
    ('Miranda', 'Centro De Servicios Caucagua'),
    ('Miranda', 'Centro De Servicios Guarenas Guatire'),
    ('Miranda', 'Centro De Servicios Rio Chico'),
    ('Miranda', 'Centro De Srvicios Eleggua'),
    ('Miranda', 'Distribuidora Fagc (valencia)'),
    ('Miranda', 'Guarenas'),
    ('Miranda', 'La Mariposa'),
    ('Miranda', 'Planta De Recuperación De Transformadores La Mariposa'),
    ('Miranda', 'Planta India Urquia'),
    ('Miranda', 'Planta Jose Maria España'),
    ('Miranda', 'Planta La Mariposa'),
    ('Miranda', 'Planta La Raisa'),
    ('Miranda', 'Planta Termoelectrica .p.i.u'),
    ('Miranda', 'S / E Santa Teresa Iii'),
    ('Miranda', 'Santa Teresa'),
    ('Miranda', 'Santa Teresa Iii'),
    ('Miranda', 'Taller Interno Santa Teresa Iii'),
    ('Miranda', 'Vehiculo Fue Desincorporado Con El No. De Sudebip 51'),
    ('Monagas', 'Caripe'),
    ('Monagas', 'Caripito / Municipio Bolivar'),
    ('Monagas', 'Jusepin'),
    ('Monagas', 'Multiservicios Palo Negro'),
    ('Monagas', 'Municipio Bolivar'),
    ('Monagas', 'Municipio Caripe'),
    ('Monagas', 'Punta De Mata'),
    ('Monagas', 'Punta De Mata / Municipio Zamora'),
    ('Monagas', 'S / E El Furrial'),
    ('Monagas', 'S / E El Indio'),
    ('Monagas', 'Sede Operativa De Corpoelec'),
    ('Monagas', 'Sede Operativa De Corpoelec La Planta'),
    ('Monagas', 'Sede Operativa La Planta'),
    ('Monagas', 'Subestacion El Furrial'),
    ('Monagas', 'Subestacion El Indio'),
    ('Monagas', 'Temblador'),
    ('Mérida', 'Av Bolivar Lagunillas Frente A La Plaza Bolivar'),
    ('Mérida', 'Av. Bolivar Lagunillas Frente A La Plaza Bolivar'),
    ('Mérida', 'Belenzate Calle La Matica'),
    ('Mérida', 'C / S Caño Zancudo'),
    ('Mérida', 'C / S Metropolitano'),
    ('Mérida', 'C / S Panamericano'),
    ('Mérida', 'C / S Panamericano El Vigia Estado Merida'),
    ('Mérida', 'Calle 16 Avenida 2 Y 3'),
    ('Mérida', 'Calle 16 Entre Av. 2 Y 3 Merida'),
    ('Mérida', 'Calle 17 Entre Avenida 2 Y 3'),
    ('Mérida', 'Calle Independecia Santo Domingo'),
    ('Mérida', 'Calle Independencia A Mucuchies'),
    ('Mérida', 'Calle Independencia Santo Domingo'),
    ('Mérida', 'Calle La Matica Urb. Belenzate'),
    ('Mérida', 'Centro De Servicio Metropolitano'),
    ('Mérida', 'Centro De Servicios Metropolitano'),
    ('Mérida', 'Centro De Servicios Nueva Bolivia'),
    ('Mérida', 'Ciau Canagua'),
    ('Mérida', 'Ciau Caño Zancudo'),
    ('Mérida', 'Ciau Caño Zancudo Santa Elelna De Arenales No. 3 - 38'),
    ('Mérida', 'Ciau Ejido'),
    ('Mérida', 'Ciau El Vigía'),
    ('Mérida', 'Ciau Lagunillas'),
    ('Mérida', 'Ciau Mucuchies'),
    ('Mérida', 'Ciau Panamericano El Vigia Estado Merida'),
    ('Mérida', 'Ciau Santo Domingo'),
    ('Mérida', 'Ciau Vigia'),
    ('Mérida', 'Cs Metropolitano Los Curos'),
    ('Mérida', 'Distribuidora Hl , Estado Merida'),
    ('Mérida', 'Distribuidora Hl ,conjunto Industrial Y Comercial San Francisco Galpon N° 12 San Cristobal Estado...'),
    ('Mérida', 'División Estadal De Atit'),
    ('Mérida', 'Dtto. Merida'),
    ('Mérida', 'Ejido Calle Industrias'),
    ('Mérida', 'Gestion De Energia'),
    ('Mérida', 'Hurtado'),
    ('Mérida', 'Merida Zona Industrial Los Curos'),
    ('Mérida', 'Ofi.canagua'),
    ('Mérida', 'Ofic. Dtto. El Vigia'),
    ('Mérida', 'Oficina Canagua'),
    ('Mérida', 'Planta Don Luis Zambrano Km17 Vigia Estado Merida'),
    ('Mérida', 'S / E El Bosque'),
    ('Mérida', 'S / E El Bosque El Vigia'),
    ('Mérida', 'Santa Elena De Arenales'),
    ('Mérida', 'Santo Domingo'),
    ('Mérida', 'Sector Santa Barbara Av Las Americas'),
    ('Mérida', 'Sector Santa Barbara Av. Las Americas'),
    ('Mérida', 'Sub Estacion Vigia I'),
    ('Mérida', 'Sub Estación Vigia I'),
    ('Mérida', 'Tovar'),
    ('Mérida', 'Tovar Carrera 3 Con Av Cristobal'),
    ('Mérida', 'Urb Belezante Calle La Matica'),
    ('Mérida', 'Urb. Belezante Calle La Matica'),
    ('Mérida', 'Urbanizacion Belezante Calle La Matica'),
    ('Mérida', 'Zona Del Vigia Km 17'),
    ('Mérida', 'Zona Industrial Los Curos'),
    ('Nueva Esparta', 'Asho'),
    ('Nueva Esparta', 'Centro De Servicio San Lorenzo'),
    ('Nueva Esparta', 'Cg Isla De Coche'),
    ('Nueva Esparta', 'Cg Juan Bautista'),
    ('Nueva Esparta', 'Cg Juan Bautista Arismendi'),
    ('Nueva Esparta', 'Cg Luisa Caceres'),
    ('Nueva Esparta', 'Cg Luisa Caceres Arismendi'),
    ('Nueva Esparta', 'Cg Planta Coche'),
    ('Nueva Esparta', 'Ciau Boca De Rio'),
    ('Nueva Esparta', 'Ciau Juan Griego'),
    ('Nueva Esparta', 'Ciau La Asuncion'),
    ('Nueva Esparta', 'Ciau Pampatar'),
    ('Nueva Esparta', 'Ciau Porlamar'),
    ('Nueva Esparta', 'Ciau Villa Rosa'),
    ('Nueva Esparta', 'Cs Juan Griego'),
    ('Nueva Esparta', 'Cs Juangriego'),
    ('Nueva Esparta', 'Cs Morropo'),
    ('Nueva Esparta', 'Cs Pampatar'),
    ('Nueva Esparta', 'Cs San Lorenso'),
    ('Nueva Esparta', 'Cs San Lorenzo'),
    ('Nueva Esparta', 'Distribucion'),
    ('Nueva Esparta', 'Infraestructura'),
    ('Nueva Esparta', 'S.e Morropo'),
    ('Nueva Esparta', 'Se Aricagua'),
    ('Nueva Esparta', 'Se Morropo'),
    ('Portuguesa', 'Acarigua'),
    ('Portuguesa', 'Almacen Nodal Acarigua (dpoa)'),
    ('Portuguesa', 'Aracoy'),
    ('Portuguesa', 'Auditoria Interna'),
    ('Portuguesa', 'Centro De Serv. Turen'),
    ('Portuguesa', 'Centro De Servicio Acarigua'),
    ('Portuguesa', 'Centro De Servicio Biscucuy'),
    ('Portuguesa', 'Centro De Servicio Guanare'),
    ('Portuguesa', 'Centro De Servicio Guanare - Guanarito'),
    ('Portuguesa', 'Centro De Servicio Turen'),
    ('Portuguesa', 'Centro Estadal De Despacho Portuguesa'),
    ('Portuguesa', 'Ciau Acarigua'),
    ('Portuguesa', 'Ciau Biscucuy'),
    ('Portuguesa', 'Ciau Guanare'),
    ('Portuguesa', 'Coord. Dpto. Operativo Control Operativo Comercial'),
    ('Portuguesa', 'Fondo Administrado Fasmee'),
    ('Portuguesa', 'Fondo Auto Administrativo De Salud Fasmee'),
    ('Portuguesa', 'Gerencia De Disrtribucion'),
    ('Portuguesa', 'Gerencia De Distribucion'),
    ('Portuguesa', 'Gerencia De Planificacion De Distrubicion De Redes'),
    ('Portuguesa', 'Gerencia Estadal De Atencion Al Ciudadano'),
    ('Portuguesa', 'Gerencia Estadal De Automatizacion De La Informacion Y Tecnologia'),
    ('Portuguesa', 'Gerencia Estadal De Bienes Y Servicios Portuguesa'),
    ('Portuguesa', 'Gerencia Estadal De Comercializacion Comercial'),
    ('Portuguesa', 'Gerencia Estadal De Control De Emergencias Industriales'),
    ('Portuguesa', 'Gerencia Estadal De Finanzas'),
    ('Portuguesa', 'Gerencia Estadal De Fiscalizacion'),
    ('Portuguesa', 'Gerencia Estadal De Fuentes Alternas Y Uso Racional Eficiente De La Energia'),
    ('Portuguesa', 'Gerencia Estadal De Prevención Y Protección'),
    ('Portuguesa', 'Gerencia Estadal De Programacion Y Control De Vegetacion'),
    ('Portuguesa', 'Gerencia Gestion Comercial'),
    ('Portuguesa', 'Gerencia Regional De Proyectos Especiales Del Sen'),
    ('Portuguesa', 'Gerencia Territorial'),
    ('Portuguesa', 'Oficina Boconoito'),
    ('Portuguesa', 'Oficina Comercial Boconoito'),
    ('Portuguesa', 'Oficina Comercial San Rafael De Onoto'),
    ('Portuguesa', 'Oficina Comercial Turen'),
    ('Portuguesa', 'Reparado En Pruebas. Talleres De La Alcaldia De Paez. G - 200027304. Acarigua Estado Portuguesa.'),
    ('Sucre', 'Alumbrado Publico'),
    ('Sucre', 'Ambiente, Seguridad E Higiene Ocupacional'),
    ('Sucre', 'C. Cumana'),
    ('Sucre', 'C.a. Cumana'),
    ('Sucre', 'Ced Sucre'),
    ('Sucre', 'Centro De Servicio Chacao'),
    ('Sucre', 'Centro De Servicios Chacao'),
    ('Sucre', 'Centro De Servicios Eleggua'),
    ('Sucre', 'Consult. Juridica'),
    ('Sucre', 'Cumana'),
    ('Sucre', 'D.d. Cumana'),
    ('Sucre', 'Div. Desarrollo'),
    ('Sucre', 'Division De Desarrollo Social'),
    ('Sucre', 'G.p. Cumana'),
    ('Sucre', 'G.r.h. Cumana'),
    ('Sucre', 'Gerencia Estadal De Ambiente, Seguridad E Higiene Ocupacional'),
    ('Sucre', 'Gerencia Estadal De Bienes Y Servicios'),
    ('Sucre', 'Gerencia Estadal De Bienes Y Servicios Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Comercializacion'),
    ('Sucre', 'Gerencia Estadal De Comercializacion Cariaco - Casanay'),
    ('Sucre', 'Gerencia Estadal De Comercializacion Carupano'),
    ('Sucre', 'Gerencia Estadal De Comercializacion Cumanacoa'),
    ('Sucre', 'Gerencia Estadal De Comercializacion Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Comercializacion Sese Cumana'),
    ('Sucre', 'Gerencia Estadal De Comercialización'),
    ('Sucre', 'Gerencia Estadal De Comunicacion Y Relaciones Publicas Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Control De Emergencia Industial Cariaco - Casanay'),
    ('Sucre', 'Gerencia Estadal De Control De Emergencia Industial Cumana'),
    ('Sucre', 'Gerencia Estadal De Control De Emergencia Industial Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Desarrollo Social Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Distribucion'),
    ('Sucre', 'Gerencia Estadal De Distribucion Cariaco'),
    ('Sucre', 'Gerencia Estadal De Distribucion Cariaco - Casanay'),
    ('Sucre', 'Gerencia Estadal De Distribucion Carupano'),
    ('Sucre', 'Gerencia Estadal De Distribucion Casanay'),
    ('Sucre', 'Gerencia Estadal De Distribucion Cumanacoa'),
    ('Sucre', 'Gerencia Estadal De Distribucion Guiria'),
    ('Sucre', 'Gerencia Estadal De Distribucion Irapa'),
    ('Sucre', 'Gerencia Estadal De Distribucion Mariguitar'),
    ('Sucre', 'Gerencia Estadal De Distribucion Pilar'),
    ('Sucre', 'Gerencia Estadal De Distribucion Rio Caribe'),
    ('Sucre', 'Gerencia Estadal De Distribucion Santa Fe'),
    ('Sucre', 'Gerencia Estadal De Distribucion Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Distribucion Sub. Canchuchu'),
    ('Sucre', 'Gerencia Estadal De Distribucion Yaguaraparo'),
    ('Sucre', 'Gerencia Estadal De Fondo Auto Administrado De Salud Fasmee'),
    ('Sucre', 'Gerencia Estadal De Fondo Auto Administrado De Salud Fasmee Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Fuentes Alternas Y Uso Racional De La Energia Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Generacion Planta Termoelectrica'),
    ('Sucre', 'Gerencia Estadal De Generacion Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Prevencion Y Proteccion'),
    ('Sucre', 'Gerencia Estadal De Prevencion Y Proteccion Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Procura'),
    ('Sucre', 'Gerencia Estadal De Procura Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Programacion Y Control De Vegetacion Cariaco - Casanay'),
    ('Sucre', 'Gerencia Estadal De Programacion Y Control De Vegetacion Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Talento Humano Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Telecomunicaciones E Informatica'),
    ('Sucre', 'Gerencia Estadal De Telecomunicaciones E Informatica Sede Cumana'),
    ('Sucre', 'Gerencia Estadal De Transmision'),
    ('Sucre', 'Gerencia Estadal De Transmision Sede Cumana'),
    ('Sucre', 'Gerencia Estadal U.r.e.e.'),
    ('Sucre', 'Gerencia Estadal U.r.e.e. Sede Cumana'),
    ('Sucre', 'Gerencia Territorial Sede Cumana'),
    ('Sucre', 'Gerenciaestadal De Comercializacion'),
    ('Sucre', 'Gerenciaestadal De Comercializacion Cumana'),
    ('Sucre', 'Gerenciaestadal De Comercializacion Sede Cumana'),
    ('Sucre', 'Global Servi J. Ca; Con Rif J - 50320749 - 3, Ubicada En Av. Nueva Esparta, Sector Venecia, Barce...'),
    ('Sucre', 'Municipio Rivero'),
    ('Sucre', 'Operativocomercial'),
    ('Sucre', 'Planif. Y Obras'),
    ('Sucre', 'Proyectos Mayores'),
    ('Sucre', 'S / E Casanay'),
    ('Sucre', 'S / S'),
    ('Sucre', 'S.i. Cumana'),
    ('Sucre', 'Sucre'),
    ('Sucre', 'T. Cumana'),
    ('Sucre', 'T.s.cumana'),
    ('Sucre', 'Transmision'),
    ('Sucre', 'U.e. Cuba'),
    ('Sucre', 'U.r.e.e. Cumana'),
    ('Trujillo', 'Almacen'),
    ('Trujillo', 'Almacen De Chatarra'),
    ('Trujillo', 'Betijoque'),
    ('Trujillo', 'Bocono'),
    ('Trujillo', 'Caja Seca'),
    ('Trujillo', 'Carache'),
    ('Trujillo', 'Centro De Servicio Convento'),
    ('Trujillo', 'Ciau Bocono'),
    ('Trujillo', 'Ciau Caja Seca'),
    ('Trujillo', 'Ciau Sab Mendoza'),
    ('Trujillo', 'Edif Mezzanotte'),
    ('Trujillo', 'Generacion'),
    ('Trujillo', 'Mezannote'),
    ('Trujillo', 'Monay'),
    ('Trujillo', 'Pampan'),
    ('Trujillo', 'Pámpan'),
    ('Trujillo', 'Sabana De Mendoza'),
    ('Trujillo', 'Sabana De Mendoza Ojo'),
    ('Trujillo', 'Sub Estacion Valera I'),
    ('Trujillo', 'Tachira - Trujillo - Valera'),
    ('Trujillo', 'Timotes'),
    ('Trujillo', 'Trujillo'),
    ('Trujillo', 'Valera'),
    ('Trujillo', 'Valera - Zonas Foraneas'),
    ('Trujillo', 'Valera / Almacen'),
    ('Trujillo', 'Valera 1'),
    ('Táchira', 'Alcaldia De Cordoba'),
    ('Táchira', 'Alcaldia De San Cristobal'),
    ('Táchira', 'Almacen Tachira'),
    ('Táchira', 'Bolivar - Ureña'),
    ('Táchira', 'Campamento Basico Santa Maria De Caparo'),
    ('Táchira', 'Canton'),
    ('Táchira', 'Central Hidroelectrica'),
    ('Táchira', 'Central Hidroelectrica Fabricio Ojeda'),
    ('Táchira', 'Central Hidroelectrica Leonardo Ruiz Pineda'),
    ('Táchira', 'Central Hidroelectrica San Agaton'),
    ('Táchira', 'Centro De Servicio San Antonio'),
    ('Táchira', 'Ch Fabricio Ojeda'),
    ('Táchira', 'Ch Leonardo Ruiz Pineda'),
    ('Táchira', 'Ciau Capacho'),
    ('Táchira', 'Ciau Colon'),
    ('Táchira', 'Ciau Coloncito'),
    ('Táchira', 'Ciau El Piñal'),
    ('Táchira', 'Ciau La Fria'),
    ('Táchira', 'Ciau La Grita'),
    ('Táchira', 'Ciau La Pedrera'),
    ('Táchira', 'Ciau Pregonero'),
    ('Táchira', 'Ciau Queniquea'),
    ('Táchira', 'Ciau Rubio'),
    ('Táchira', 'Ciau San Antonio'),
    ('Táchira', 'Ciau San Crsitobal Iii'),
    ('Táchira', 'Ciau Santa Ana'),
    ('Táchira', 'Ciau Tariba'),
    ('Táchira', 'Ciau Ureña'),
    ('Táchira', 'Colon'),
    ('Táchira', 'Coloncito - La Tendida'),
    ('Táchira', 'Cs La Fria'),
    ('Táchira', 'Cs San Antonio'),
    ('Táchira', 'Distrito San Cristobal'),
    ('Táchira', 'Division Control De Operaciones'),
    ('Táchira', 'Division Regional'),
    ('Táchira', 'Dpto Atc Averias Cs Tb San Cristobal'),
    ('Táchira', 'Dpto Mtto Cs Tb San Cristobal'),
    ('Táchira', 'Edf. Zona Tachira'),
    ('Táchira', 'El Pinar'),
    ('Táchira', 'El Piñal'),
    ('Táchira', 'Gerencia Regional Generacion Hidroelectrica'),
    ('Táchira', 'Junin - Delicias'),
    ('Táchira', 'La Fria'),
    ('Táchira', 'La Grita'),
    ('Táchira', 'La Pedrera'),
    ('Táchira', 'La Tendida'),
    ('Táchira', 'Piñal - Pedrera'),
    ('Táchira', 'Planta Tachira'),
    ('Táchira', 'Planta Tachra'),
    ('Táchira', 'Pregonero'),
    ('Táchira', 'Pregonero - San Agaton'),
    ('Táchira', 'Puente Real'),
    ('Táchira', 'Rubio'),
    ('Táchira', 'Rubio - Delicias'),
    ('Táchira', 'S / E San Cristobal I Oficina Principal'),
    ('Táchira', 'Sag Edificio Zona 7'),
    ('Táchira', 'San Antonio'),
    ('Táchira', 'San Antonio - Ureña'),
    ('Táchira', 'San Cristobal'),
    ('Táchira', 'San Cristobal I'),
    ('Táchira', 'San Cristobal Iii'),
    ('Táchira', 'Santa Ana'),
    ('Táchira', 'Sub Estaciones'),
    ('Táchira', 'Tachira'),
    ('Táchira', 'Taller De Corpoelec'),
    ('Táchira', 'Trasporte'),
    ('Táchira', 'Uribante Caparo'),
    ('Táchira', 'Zona 7'),
    ('Yaracuy', 'C / S Independencia'),
    ('Yaracuy', 'C / S Nirgua'),
    ('Yaracuy', 'Centro De Servicio Independencia'),
    ('Yaracuy', 'Centro De Servicio San Felipe'),
    ('Yaracuy', 'Est.rr.humanos Yaritagua'),
    ('Yaracuy', 'Estacionamiento Almacen Yaritagua'),
    ('Yaracuy', 'Estacionamiento Oficina Aroa'),
    ('Yaracuy', 'Estacionamiento Oficina Chivacoa'),
    ('Yaracuy', 'Estacionamiento Planta Turbo Gas'),
    ('Yaracuy', 'Nirgua'),
    ('Yaracuy', 'S / E San Felipe'),
    ('Yaracuy', 'S / E San Felipe 2'),
    ('Yaracuy', 'San Felipe'),
    ('Yaracuy', 'Sub - Estacion Chivacoa'),
    ('Yaracuy', 'Sub - Estacion Yaracuy 765 / 400 / 230 "las Velas'),
    ('Yaracuy', 'Subestacion Yaracuy'),
    ('Yaracuy', 'Taller De Flota Lara'),
    ('Yaracuy', 'Turbo Gas'),
    ('Yaracuy', 'Yaritagua'),
    ('Yaracuy', 'Yaritagua Zona'),
    ('Zulia', '19 De Abril'),
    ('Zulia', '19 De Abril Cabimas'),
    ('Zulia', 'Baralt'),
    ('Zulia', 'Cabimas'),
    ('Zulia', 'Casigua'),
    ('Zulia', 'Cañada De Urdaneta'),
    ('Zulia', 'Centro De Operaciones Caujarito'),
    ('Zulia', 'Centro De Operaciones Maguapa'),
    ('Zulia', 'Concepcion'),
    ('Zulia', 'Electra Representaciones'),
    ('Zulia', 'Guajira'),
    ('Zulia', 'Isla'),
    ('Zulia', 'La Villa'),
    ('Zulia', 'Lagunillas'),
    ('Zulia', 'Machiques'),
    ('Zulia', 'Maracaibo'),
    ('Zulia', 'Maracaibo (caujarito)'),
    ('Zulia', 'Maracaibo (cota)'),
    ('Zulia', 'Maracaibo (prl)'),
    ('Zulia', 'Mene Grande'),
    ('Zulia', 'Miranda'),
    ('Zulia', 'Mojan'),
    ('Zulia', 'Planta Termo Zulia'),
    ('Zulia', 'San Francisco'),
    ('Zulia', 'San Francisco (termozulia)'),
    ('Zulia', 'San Lorenzo'),
    ('Zulia', 'Santa Barbara'),
    ('Zulia', 'Santa Rita'),
    ('Zulia', 'Tablazo'),
    ('Zulia', 'Termozulia'),
    ('Zulia', 'Zulia'),
]


MARCAS = [
    'Allis Chalmers',
    'Andino',
    'Argeven',
    'BAW',
    'Beretta',
    'Busscar',
    'CHL',
    'Caribe',
    'Caterpillar',
    'Chama',
    'Chery',
    'Chevrolet',
    'Clark',
    "D'Innocenzo",
    'DFSK',
    'Daewoo',
    'Dayun',
    'Dodge',
    'Doll',
    'Domosa',
    'Dongfeng',
    'Doosan',
    'Empire Keeway',
    'Encava',
    'Escuda',
    'Farrenaca',
    'Favemo',
    'Fiat',
    'Flatbed',
    'Ford',
    'Forza',
    'Foton',
    'Freelander',
    'Fruget',
    'Fuwa',
    'General Motors',
    'Genie',
    'Golden Dragon',
    'Grove',
    'HLI',
    'Haojue',
    'Haweca',
    'Heli',
    'Higer',
    'Hino',
    'Honda',
    'Hyster',
    'Hyundai',
    'IKCO',
    'International',
    'Isuzu',
    'Iveco',
    'JMC',
    'Jac',
    'Jeep',
    'Jlg',
    'John Deere',
    'KTM',
    'Kawasaki',
    'Kenworth',
    'Kia',
    'King',
    'Komatsu',
    'Laval',
    'Liebherr',
    'Link-Belt',
    'Mack',
    'Man',
    'Maximall',
    'Mazda',
    'Mercedes-Benz',
    'Mitsubishi',
    'New Holland',
    'Nifty',
    'Nissan',
    'Orinoco',
    'P&H',
    'Pegaso',
    'Peugeot',
    'Power Sport',
    'Raly',
    'Random',
    'Rely',
    'Remolque',
    'Remyveca',
    'Renault',
    'Reward',
    'Reyco',
    'Rockford',
    'Saipa',
    'San Cristóbal',
    'Scania',
    'Sinotruk',
    'Suzuki',
    'Swing Energy',
    'TCM',
    'Tadano',
    'Tekken',
    'Terex',
    'Toyota',
    'Traimobile',
    'Tupamet',
    'Venezuela',
    'Veniran',
    'Volkswagen',
    'XCMG',
    'Yale',
    'Yamaha',
    'Yutong',
    'Zoomlion',
]


MODELOS = {
    'Allis Chalmers': [
        'Monta Carga',
    ],
    'Andino': [
        'Fg30t',
        'Monta Carga',
        'Montacarga',
        'Tan 30 - Pg',
    ],
    'Argeven': [
        'Unidad Movil',
    ],
    'BAW': [
        '5021xxy6zb4',
    ],
    'Beretta': [
        'Chimana 9.22m',
        'Evolution',
    ],
    'Busscar': [
        'Autobus',
        'Bus Star',
        'Kamaz',
    ],
    'CHL': [
        'Montacarga',
    ],
    'Caribe': [
        'Caribe',
    ],
    'Caterpillar': [
        '10 Ton',
        'Dp - 50k',
        'Dp 40k1',
        'Dp135',
        'Dp35 - D',
        'Dp40k1',
        'Dp50k',
        'Fg 30t',
        'Monta Carga',
        'Montacarga',
        'Montacargas',
        'P33000',
        'P6000 - Lp',
        'P6000 Lp',
        'Tractor D - 4e',
        'Tractor D - 8k',
        'V10',
        'V100',
    ],
    'Chama': [
        'Batea',
        'Low Boy',
    ],
    'Chery': [
        'Arauca',
        'X1',
    ],
    'Chevrolet': [
        'Ambulancia',
        'Arauca',
        'Autobus',
        'Buick',
        'C-10',
        'C-30',
        'C-31',
        'C-3500',
        'C-60',
        'C30',
        'Camion',
        'Camioneta',
        'Captiva',
        'Caribe',
        'Cava',
        'Cava Con Termoking',
        'Cavalier',
        'Celebriti',
        'Cesta',
        'Cesta Hidraul.',
        'Cheyenne',
        'Cisterna Para Lavado',
        'Colorado',
        'Comioneta Van',
        'Cruze',
        'D21',
        'Equip. Hidraul.',
        'Estaca',
        'Express',
        'Exr',
        'F - 350',
        'F - 350 Unicesta',
        'F - 4000',
        'F - 7000',
        'FVR',
        'FVR Grua',
        'G. Blazer',
        'Grand Vitara',
        'Hilux',
        'Jimny',
        'Kodiak',
        'LUV D-Max',
        'Malibú',
        'Montana',
        'NHR',
        'NKR',
        'NPR',
        'Optra',
        'P - 31',
        'Panel',
        'Pick - Up',
        'Pick - Up Cabina - Camioneta',
        'Pick Up',
        'Pickup',
        'S-10',
        'Sedan',
        'Silverado',
        'Super Carry',
        'Swift',
        'Titan',
        'Unicesta',
        'Unidad Movil',
        'Vans',
        'Vitara',
    ],
    'Clark': [
        'Cmo50sd',
        'Monta Carga',
        'Montacargas',
    ],
    "D'Innocenzo": [
        'C - 60 - D - J3',
    ],
    'DFSK': [
        'C35',
    ],
    'Daewoo': [
        'Damas',
        'Lanos Sx',
    ],
    'Dayun': [
        '150 Cc',
        '150cc',
        '200',
        'Barandas',
        'Barranda',
        'Cajon Dos Aguas',
        'Cajon Plano',
        'Dc200v - 1',
        'Trimoto',
    ],
    'Dodge': [
        'D - 300',
        'Dakota Cr 4X4 D / C',
        'Equip. Hidraul.',
        'Grua',
        'Ram',
        'T4000',
        'Town',
    ],
    'Doll': [
        'T4h0s3',
    ],
    'Domosa': [
        'Tb547 / 42',
    ],
    'Dongfeng': [
        'Camion',
        'Camion Plataforma',
        'Camioneta Doble Cabina',
        'Cesta',
        'Cuadrillero',
        'DFL',
        'Duolika7t',
        'KR',
        'Md6833',
        'Mini Truck',
        'Pick Up Doble Cabina',
        'Star',
        'U - Uvan',
        'Yc4e1630',
        'ZNA',
        'Zk6860dbus',
    ],
    'Doosan': [
        'D45s - 2',
        'D50sc - 5',
    ],
    'Empire Keeway': [
        'C - 150',
        'Ek Express 150',
        'Txen 200',
    ],
    'Encava': [
        'Ent - 610',
        'Ent - 900',
        'Ent3300',
        'Ep1000',
    ],
    'Escuda': [
        'Sin Especificar',
    ],
    'Farrenaca': [
        'Batea',
        'Batea Plataforma',
        'Low Boy',
    ],
    'Favemo': [
        'Sin Especificar',
    ],
    'Fiat': [
        'Camioneta',
        'Ducato',
        'Ducato Maxicargo',
        'Estaca',
        'Fiorino',
        'Montacarga',
        'Palio',
        'Premio',
        'Uno',
        'Uno Fire',
    ],
    'Flatbed': [
        'Ytz9400tpb',
        'Ytz9401tdp',
    ],
    'Ford': [
        '250',
        '7400 SBA',
        'Ambulancia',
        'Autobus',
        'Autobus Super Dutty',
        'Bronco',
        'C - 3500',
        'C - 3500 Plataforma',
        'C - 3500 Unicesta',
        'Cabina',
        'Cabina Y Chassis',
        'Cajon',
        'Cajon Gavetero',
        'Camión',
        'Canina',
        'Carga',
        'Cargo',
        'Cargo815',
        'Cesta',
        'Chassis',
        'Comioneta Van',
        'Conquistador',
        'Dm10a',
        'Doble Cesta',
        'E-350',
        'Eq. Perforador',
        'Equipo Especial',
        'Equipo Hidráulico',
        'Escalera',
        'Estaca',
        'Euquipo Hidr.',
        'Explorer',
        'F - 1317',
        'F - 1517',
        'F - 700',
        'F-150',
        'F-350',
        'F-4000',
        'F-450',
        'F-550',
        'F-600',
        'F-7000',
        'F-8000',
        'FVR',
        'Focus',
        'Fortaleza',
        'Fx4',
        'L - 8000',
        'Laser',
        'Lavado',
        'Multi Uso',
        'Munck',
        'Pick - Up',
        'Pick - Up 4 X 2',
        'Pick - Up 4 X 4',
        'Pick Up',
        'Pick Up Doble Cabina',
        'Pickup',
        'Pickup - F250',
        'Plataforma',
        'Ranger',
        'Sedan',
        'Sport Wagon',
        'Super Duty',
        'Transit',
        'Triton',
        'Unicesta',
        'Unicesta 4000',
        'Vans',
    ],
    'Forza': [
        '250',
    ],
    'Foton': [
        'Auman',
        'Auman Etx 2527',
        'Bj4259sfkb - Aj',
        'Camion Cisterna',
        'Chuto',
        'Cisterna',
    ],
    'Freelander': [
        'Batea',
    ],
    'Fruget': [
        'Batea Plataforma',
    ],
    'Fuwa': [
        '3 Ejes',
        'Batea Plataforma',
        'Cisterna',
        'Fw280022',
        'Low Boy',
    ],
    'General Motors': [
        'C - 10',
        'Topkick C7500',
    ],
    'Genie': [
        'Z4525',
    ],
    'Golden Dragon': [
        'Neveri',
    ],
    'Grove': [
        'Gmk40801',
        'Grua Telescopica 30 Tn',
        'Rt700e',
        'Rt890e',
        'Tms250c',
    ],
    'HLI': [
        'Cpc025',
    ],
    'Haojue': [
        '150',
        '250',
        'F - 1517',
        'Ii',
        'J1soii',
        'Moto',
        'Moto 2 Ruedas',
        'Moto Carga',
        'Motos Dos Ruedas',
        'Pj',
    ],
    'Haweca': [
        'Sin Especificar',
    ],
    'Heli': [
        '88 - G35',
        'Cpcd50',
        'Cpqyd25',
        'Montacargas',
    ],
    'Higer': [
        'Autobus',
        'Michelena',
    ],
    'Hino': [
        '300',
        '616',
        '816',
        'Cava Con Termoking',
        'Chasis',
    ],
    'Honda': [
        'Sin Especificar',
    ],
    'Hyster': [
        'E70 - 120xl3',
        'Grua',
        'H2.5tx - 2t',
        'Montacarga',
    ],
    'Hyundai': [
        'Elantra',
        'H100 Plataforma',
        'Hdf 50 - 7s',
        'Sedan',
    ],
    'IKCO': [
        'Sin Especificar',
    ],
    'International': [
        '3700',
        '4300',
        '4400 SBA',
        '4900',
        '7000',
        '7400',
        'Angr13',
        'CF-500',
        'Cabina Y Chassis',
        'Cami0n',
        'Camion',
        'Carga',
        'Cesta',
        'Equip. Hidraul.',
        'Grua',
        'Grua Pitman',
        'Paystar',
        'Pitman',
        'Plataforma',
        'Tipo Cesta',
        'Unicesta',
        'Work Star',
    ],
    'Isuzu': [
        'Batea',
        'Camion Cesta',
        'Camioneta',
        'Caribe',
        'Caribe 442',
        'Cesta',
        'Elf',
        'Forward',
        'Forward - Fv',
        'Grua Pitman',
        'Npr6sn',
        'Reward',
        'Reward - Np',
        'Rewuard - Np',
        'Vdr - 320',
    ],
    'Iveco': [
        '1.7e+24',
        '40 - 12',
        'Autobus',
        'Bus',
        'Camion Cesta',
        'Camion Grua Cesta',
        'Cesta',
        'Chasis',
        'Daily',
        'Equipo Hidraulico',
        'Eurocargo',
        'Grua Pitman',
        'Pitman',
        'Tector',
        'Trakker',
        'Unicesta',
    ],
    'JMC': [
        'Carrying',
        'Carryng',
        'Conauer',
        'Touring',
    ],
    'Jac': [
        'Cpoy30',
        'Hfc 1061k',
        'Hfc1061k Unicesta',
    ],
    'Jeep': [
        '810 Cj - Wrangler Techo Duro',
        'Camioneta',
        'Cherokee',
        'Cherokee Chief',
        'Cj - 5',
        'Cj - 7',
        'Cj Wrangler',
        'Cj Wrangler T. Duro',
        'Limited Cj - 7',
        'Renegado',
        'Techo Duro',
        'Willys',
        'Wlangler',
        'Wrangler',
        'Wrangler Basico',
    ],
    'Jlg': [
        'E450aj',
    ],
    'John Deere': [
        '644e',
        '6603 Mfwd',
        '6605 Cabinado',
        'Turbo Syncshuttle',
    ],
    'KTM': [
        '640lc - 4',
        'Lt4',
    ],
    'Kawasaki': [
        'Kl650edfk / Klr',
    ],
    'Kenworth': [
        'Sin Especificar',
    ],
    'Kia': [
        'Pregio',
    ],
    'King': [
        '4sw',
    ],
    'Komatsu': [
        'Fde35155',
        'Montacarga 3 Toneladas (fg30nt)',
    ],
    'Laval': [
        'Cisterna',
    ],
    'Liebherr': [
        'Grua 200 Ton',
        'Utm 855',
    ],
    'Link-Belt': [
        'Grua Telescopica 30 Tn',
    ],
    'Mack': [
        'Ch613hd',
        'Chuto',
        'R600',
    ],
    'Man': [
        'At 4000 Tgm 18.280',
        'Panther 3000 Hret Mixmatic Man Tga 33.350',
        'Rosembauer 600300100 Bombero',
        'Rosenbauer',
        'Ulf / 3000 / 5000 / Mi.xh.hret',
        'Ulf Hret Mixmatic Man Tga 33.350',
    ],
    'Maximall': [
        'Fd50t9',
    ],
    'Mazda': [
        'B2600',
        'Bt - 50',
        'Bt50',
    ],
    'Mercedes-Benz': [
        '0400rse',
        '413 Sprinter',
        '711',
        'Oh142051a',
        'Plata Forma',
    ],
    'Mitsubishi': [
        'Camion',
        'Camion Plataforma',
        'Canter',
        'Carter',
        'Equip. Hidraul.',
        'Fg25nt',
        'L200',
        'Monta Carga',
        'Montacarga 3 Toneladas (fg30nt)',
        'Montero',
        'Pick - Up',
        'Signo Gli',
        'Sport Wagon',
    ],
    'New Holland': [
        'Tractor',
    ],
    'Nifty': [
        'Hr15 Nde',
    ],
    'Nissan': [
        'Almera',
        'Camioneta',
        'Camioneta Pick - Up',
        'D21',
        'Frontier',
        'Montacarga',
        'NP300',
        'Pick - Up D / C',
        'Pick - Up D / Cabina Diesel',
        'Pick Up',
        'Sentra',
        'Setra Gxe T / A',
    ],
    'Orinoco': [
        'Sin Especificar',
    ],
    'P&H': [
        'Sin Especificar',
    ],
    'Pegaso': [
        'Camion 7000',
    ],
    'Peugeot': [
        'Partner',
    ],
    'Power Sport': [
        'Sin Especificar',
    ],
    'Raly': [
        'Tmax',
    ],
    'Random': [
        'Dlblct0240',
        'Sr Cs Mt 03 35',
    ],
    'Rely': [
        'Tmax',
    ],
    'Remolque': [
        'Psi',
        'Tc2er24',
    ],
    'Remyveca': [
        '3re24.110',
        'Polar',
    ],
    'Renault': [
        'Sedan',
    ],
    'Reward': [
        'Isuzu',
    ],
    'Reyco': [
        'Sin Especificar',
    ],
    'Rockford': [
        'Carga Con Propulsion',
        'Mot. Gasoil',
        'Motobomba',
    ],
    'Saipa': [
        'Quick',
        'Saina',
        'Sedan',
    ],
    'San Cristóbal': [
        '2 Ejes',
    ],
    'Scania': [
        'P310',
    ],
    'Sinotruk': [
        '420hp 6X4',
        'Chuto',
        'Homo',
        'Howo 7',
        'Howo7',
        'Zz4257v3247n1b',
    ],
    'Suzuki': [
        '150cc',
        '200',
        '200cc',
        'DR200',
        'En',
        'GN125',
        'Grand Vitara',
        'Vestron 650',
        'XEN125',
    ],
    'Swing Energy': [
        'Sin Especificar',
    ],
    'TCM': [
        'F050t9',
        'Fd25t3z',
        'Fd5019',
        'Fd50t9',
        'Fd50ta',
        'Monta Carga',
        'Montacargas',
    ],
    'Tadano': [
        'Grua 50 Ton',
    ],
    'Tekken': [
        'Sin Especificar',
    ],
    'Terex': [
        'Rt780',
    ],
    'Toyota': [
        '711',
        'Autana',
        'Celebriti',
        'Cesta',
        'Coaster',
        'Corolla',
        'Dyna',
        'Esc. Mecanica',
        'Estaca',
        'F - 350 Ferretero',
        'FVR',
        'Hiace',
        'Hilux',
        'Land Cruiser',
        'Malibu',
        'Meru',
        'Montacarga',
        'Samurai',
        'Sport Wagon',
        'Tacoma',
        'Tipo Cesta',
        'Unicesta',
        'Vans',
        'Yaris',
    ],
    'Traimobile': [
        'Td - 50 - F',
    ],
    'Tupamet': [
        '3 Ejes',
    ],
    'Venezuela': [
        '3 Ejes',
    ],
    'Veniran': [
        '399 4WD',
        '3994wd',
        '400 4WD',
    ],
    'Volkswagen': [
        '17220',
        'Golf',
    ],
    'XCMG': [
        'Grua De 100 Ton',
        'Quy55',
        'Qy100ki',
        'Qy160ki',
        'Ty230',
    ],
    'Yale': [
        'Gp30te',
        'Gtp30tk',
        'Monta Carga',
    ],
    'Yamaha': [
        'Kl650edfk / Klr',
    ],
    'Yutong': [
        '140',
        '3 Ejes',
        'Batea',
        'Bus',
        'Bus Rural',
        'Bus Urbano',
        'Low - Boy',
    ],
    'Zoomlion': [
        'Grua 50 Ton',
    ],
}


COLORES = [
    'Amarillo',
    'Azul',
    'Beige',
    'Blanco',
    'Dorado',
    'Fucsia',
    'Gris',
    'Naranja',
    'Negro',
    'Plateado',
    'Rojo',
    'Verde',
    'Vinotinto',
]


ESTATUS = [
    'Desincorporado',
    'En reparación',
    'Hurtado',
    'Inoperativo',
    'Operativo',
    'Otros Entes',
    'Por Desincorporar',
    'Por Ubicar',
]


CLASES_VEHICULO = [
    'Liviano',
    'Mediano',
    'Pesado',
    'Especial',
    'Remolque',
    'Acuático',
]

TIPOS_COMBUSTIBLE = [
    'Gasolina',
    'Diesel',
]
