# Generated by Django 5.2.15 on 2026-07-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
                ('sistema_afectado', models.CharField(max_length=50, verbose_name='Sistema afectado')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Tipo de falla',
                'verbose_name_plural': 'Tipos de falla',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Tipo de uso',
                'verbose_name_plural': 'Tipos de uso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca__nombre', 'nombre'],
                'unique_together': {('nombre', 'marca')},
            },
        ),
    ]
