# Generated by Django 5.2.15 on 2026-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_sistema_afectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Estatus de vehículo',
                'verbose_name_plural': 'Estatus de vehículos',
                'ordering': ['nombre'],
            },
        ),
    ]
