# Generated by Django 5.2.15 on 2026-07-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_estatusvehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Color de placa',
                'verbose_name_plural': 'Colores de placa',
                'ordering': ['nombre'],
            },
        ),
    ]
