# Generated by Django 5.2.15 on 2026-07-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_colorplaca'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='colorplaca',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estatusvehiculo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sistemaafectado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipofalla',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipouso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_color_nombre'),
        ),
        migrations.AddConstraint(
            model_name='colorplaca',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_colorplaca_nombre'),
        ),
        migrations.AddConstraint(
            model_name='estatusvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_estatusvehiculo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_marca_nombre'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre', 'marca'), name='unique_active_modelo_nombre_marca'),
        ),
        migrations.AddConstraint(
            model_name='sistemaafectado',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_sistemaafectado_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tipofalla',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('descripcion',), name='unique_active_tipofalla_descripcion'),
        ),
        migrations.AddConstraint(
            model_name='tipouso',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_tipouso_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tipovehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_tipovehiculo_nombre'),
        ),
    ]
