# Generated by Django 5.2.15 on 2026-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_seed_catalog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Clase de vehículo',
                'verbose_name_plural': 'Clases de vehículo',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_clasevehiculo_nombre')],
            },
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
            ],
            options={
                'verbose_name': 'Tipo de combustible',
                'verbose_name_plural': 'Tipos de combustible',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('nombre',), name='unique_active_tipocombustible_nombre')],
            },
        ),
    ]
