# Generated by Django 5.2.15 on 2026-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_clasevehiculo_tipocombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatusvehiculo',
            name='es_operativo',
            field=models.BooleanField(default=True, verbose_name='¿Es operativo?'),
        ),
    ]
