# Generated by Django 5.2.15 on 2026-06-19 01:49

from django.db import migrations


def migrate_gerencia_estado(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    for user in Usuario.objects.select_related("gerencia__estado").iterator():
        if user.gerencia and user.gerencia.estado_id and not user.estado_id:
            user.estado = user.gerencia.estado
            user.save(update_fields=["estado"])


class Migration(migrations.Migration):

    dependencies = [
        ("organizacion", "0001_initial"),
        ("usuarios", "0002_add_estado_to_usuario"),
    ]

    operations = [
        migrations.RunPython(migrate_gerencia_estado, migrations.RunPython.noop),
    ]
