# Generated by Django 5.2.15 on 2026-06-22 13:33

from django.db import migrations, models


def migrate_role_values(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(rol="gerente_nacional").update(rol="nacional")
    Usuario.objects.filter(rol="responsable_estatal").update(rol="estatal")
    Usuario.objects.filter(rol="analista_nacional").update(rol="analista")


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_migrate_gerencia_estado_to_user"),
    ]

    operations = [
        migrations.RunPython(migrate_role_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="usuario",
            name="gerencia",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("nacional", "Nacional"),
                    ("estatal", "Estatal"),
                    ("analista", "Analista"),
                    ("mecanico", "Mecánico"),
                ],
                max_length=25,
                verbose_name="Rol",
            ),
        ),
    ]
