# Generated by Django 5.2.15 on 2026-07-04 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0005_colorplaca'),
        ('organizacion', '0004_centrodeservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=50, unique=True, verbose_name='Número económico (Activo SAP)')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN / Serial de chasis')),
                ('numero_unidad', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de unidad')),
                ('placa_intt', models.CharField(blank=True, max_length=20, verbose_name='Placa INTT')),
                ('serial_motor', models.CharField(blank=True, max_length=50, verbose_name='Serial de motor')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('codigo_qr', models.TextField(blank=True, verbose_name='Código QR')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus activo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipovehiculo', verbose_name='Categoría')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.color', verbose_name='Color')),
                ('color_placa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.colorplaca', verbose_name='Color de placa')),
                ('emplazamiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.centrodeservicio', verbose_name='Emplazamiento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.estado', verbose_name='Estado')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.estatusvehiculo', verbose_name='Estatus')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizacion.gerencia', verbose_name='Gerencia')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['numero_economico'],
                'constraints': [models.UniqueConstraint(fields=('placa', 'color_placa'), name='unique_placa_por_color')],
            },
        ),
    ]
