# Generated by Django 5.2.15 on 2026-07-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_colorplaca'),
        ('organizacion', '0004_centrodeservicio'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='unidad_usuaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehiculos_usuarios', to='organizacion.gerencia', verbose_name='Unidad usuaria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color_placa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.colorplaca', verbose_name='Color de placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa'),
        ),
    ]
