# Generated by Django 5.2.15 on 2026-07-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_modelo_unique_together_alter_color_nombre_and_more'),
        ('organizacion', '0005_alter_centrodeservicio_nombre_alter_estado_nombre_and_more'),
        ('vehiculos', '0002_vehiculo_unidad_usuaria_alter_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiculo',
            name='unique_placa_por_color',
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus_activo', True)), fields=('placa', 'color_placa'), name='unique_active_vehiculo_placa_color_placa'),
        ),
    ]
