# Generated by Django 5.2.15 on 2026-07-08 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_modelo_unique_together_alter_color_nombre_and_more'),
        ('vehiculos', '0003_remove_vehiculo_unique_placa_por_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipouso', verbose_name='Tipo de uso'),
        ),
    ]
