# Generated by Django 5.2.15 on 2026-07-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_clasevehiculo_tipocombustible'),
        ('vehiculos', '0005_vehiculo_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='idx_vehiculo_activo_estado',
        ),
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='idx_vehiculo_estatus',
        ),
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='idx_vehiculo_gerencia',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.clasevehiculo', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipocombustible', verbose_name='Tipo de combustible'),
        ),
    ]
