# Generated by Django 5.2.15 on 2026-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_backfill_clase_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_economico',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número económico'),
        ),
    ]
